version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sheepify_postgres
    environment:
      POSTGRES_USER: sheepify_user
      POSTGRES_PASSWORD: sheepify_pass
      POSTGRES_DB: sheepify
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sheepify_user -d sheepify"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
